***Forløbsplan : uge 34 - mandag d.21/8***

| Uge 34                 | arbejdsform       | indhold                                                                                                                                                                                                                                |
|------------------------|-------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ***Mandag 21.august*** |                   |                                                                                                                                                                                                                                        |
| 4. modul               | intro i klasser   | [løsning på solsystem-opgaven](https://github.com/digitaltdesignlyngby/solsystem_opgaven) <br/> [ løsning på solsystem-opgaven med flere Nodes](https://github.com/digitaltdesignlyngby/solsystem2)                                    |
| 5. modul               | arbejd selv       | [from zero](https://gdquest.github.io/learn-gdscript/)  (lav resten...)                                                                                                                                                                |
| 6. modul               | arbejd selv       | [docs 3.5 - script basics](https://docs.godotengine.org/en/3.5/tutorials/scripting/gdscript/index.html) <br/><br/>  [små opgaver og indbyggede funktioner](opgaver_basic.pdf) <br/> [opgave i brug af inner classes](opgave_draaber.md) <br/> [opgave i modulo lyskryds](opgave_lyskryds.md)    |
|                        |                   |                                                                                                                                                                                                                                        |
| ***Onsdag 23.august*** |                   |                                                                                                                                                                                                                                        |
| 4. modul               | intro i klasser   | løsning på skakbræt-opgaven                                                                                                                                                                                                            |
| 6. modul               | arbejd selv       | [docs 3.5 - vektorer](https://docs.godotengine.org/en/stable/tutorials/math/vector_math.html#)                                                                                                                                         |
| 7. modul               | arbejd selv       | [opgaven follower](opgave_follower.html) <br/> [opgaven lykkehjul](opgave_lykkehjulet.pdf)                                                                                                                                             |


***Forløbsplan : uge 35 - mandag d.28/8***

| Uge 35                 | arbejdsform       | indhold                                                                                                                                                                                                                                |
|------------------------|-------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ***Mandag 28.august*** |                   |                                                                                                                                                                                                                                        |
| 4. modul               | intro i klassen   | løsning på follower opgaven                                                                                                                                                                                                            |
| 5. modul               | arbejd  selv      | [læs: nature of code ,chap6: auto-agents](https://natureofcode.com/book/chapter-6-autonomous-agents/) <br/> Lav eksemplerne i Godot med gdscript                                                                                       |
|                        |                   |                                                                                                                                                                                                                                        |
| ***Onsdag 30.august*** |                   |                                                                                                                                                                                                                                        |
| 4. modul               | intro i klasser   | løsning follower med acceleration og tilfældig bevægelse                                                                                                                                                                               |
| 5. modul               | arbejd  selv      | [Nedarvnings opgave : Predator og Prey](opgave_follower_nedarvning.md)  <br/>  [opgave scene-skift](opgave_scene_skift.pdf)                                                                                                            |


Næste gang objektorienteret programmering med gdscript ...